const projetData = {
  1: {
    "cover": "magicball",
    "name": "MagicBall",
    "categorie": "Intégration",
    "contexte": "Dans le cadre de ma formation en BUT MMI, j’ai développé une application web dédiée à la gestion d'une collection de Pokémon.",
    "objectifs": "L’objectif était de concevoir une interface personnalisée permettant à un utilisateur unique de consulter et d'organiser l'ensemble de sa collection de manière fluide.",
    "etapes": ["Conception d'une planche univers", "Réalisation d'une maquette en version papier", "Création d’une maquette numérique", "Production du site en HTML / CSS / JS"],
    "soft_skills": ["Autonomie", "Créativité"],
    "hard_skills": ["Intégration",
      "Wireframing",
      "Maquette numérique"],
    "outils": ["figma", "html", "css", "js"],
    "prototype": "projet/magicball.pdf",
  },
  2: {
    "cover": "autoportrait",
    "name": "Autoportrait",
    "categorie": "Graphisme",
    "contexte": "Dans le cadre d’un projet en BUT MMI, j’ai conçu un autoportrait graphique destiné à devenir le support d’une expérience interactive.",
    "objectifs": "L’enjeu était d'utiliser mes propres éléments visuels comme base pour développer une interaction dynamique et cohérente.",
    "etapes": ["Recherche graphique", "Réalisation d'une première version de mon autoportrait", "Finitions des retouches l'aspects graphique", "Création de l'interaction en javascript"],
    "soft_skills": ["Sens du détail", "Créativité"],
    "hard_skills": ["Javascript",
      "Design graphique"],
    "outils": ["affinity", "html", "css", "js"],
    "prototype": "projet/ap.pdf",
  },
  3: {
    "cover": "laconfiserie",
    "name": "La Confiserie",
    "categorie": "Développement Web",
    "contexte": "Dans le cadre d’un projet universitaire en BUT MMI, j’ai réalisé un site web en binôme dont le but était de concevoir un réseau de boutiques de confiserie en PHP et SQL.",
    "objectifs": "L’objectif était de créer un site Web en adéquation avec les valeurs et l’histoire de l'entreprise, tout en répondant aux exigences requises notamment la gestion des rôles, des stocks ainsi que des boutiques.",
    "etapes": ["Réalisation d’une planche tendance de la marque", "Structuration de l’information des différentes pages et fonctionnalités (Wireframes)", "Création d’une maquette numérique", "Établissement de la base de donnée","Conception du site en PHP" ],
    "soft_skills": ["Travail d'équipe", "Autonomie"],
    "hard_skills": ["UX/UI Design", "Wireframing", "Maquette numérique",
      "Développement Web"],
    "outils": ["figma", "php", "sql", "js"],
    "prototype": "projet/confiserie.pdf",
  },
  4: {
      "cover": "infographie",
    "name": "Réseaux de neurones",
    "categorie": "Graphisme",
    "contexte": "Dans le cadre d'un projet en BUT MMI, j'ai conçu une infographie pour la Fête de la Science.",
    "objectifs": "L'enjeu était de transformer des données complexes en un support visuellement attrayant, tout en garantissant une hiérarchie de l'information claire et cohérente.",
    "etapes": ["Choix du sujet basé sur l'IA", "Recherche graphique", "Réalisation d'une première version de l'affiche", "Finitions des retouche pour la version finale de l'affiche" ],
    "soft_skills": ["Être rafiner", "Créativité"],
    "hard_skills": ["Infographie", "Design graphique"],
    "outils": ["affinity", "pinterest"],
    "prototype": "projet/Infographie.pdf",
  },
  5: {
    "cover": "locfit",
    "name": "Locfit",
    "categorie": "UX/UI Design",
    "contexte": "Dans le cadre d’un projet universitaire en BUT MMI, j’ai réalisé un site web en groupe de 4 dont le but était de concevoir un site spécialisé dans la vente et la location de produits de sport.",
    "objectifs": "L’objectif était de créer une application web de location de matériel sportif à partir d'un persona donné. Pour ensuite créer le site en EJS.",
    "etapes": ["Établissement d'une carte heuristique à partir du persona", 
      "Réalisation d'un benchmark sur la concurrence", 
      "Conception d'une planche univers", 
      "Construction d'une charte graphique",
    "Structuration de l’information des différentes pages et fonctionnalités (Wireframes)",
    "Création d’une maquette numérique",],
    "soft_skills": ["Travail d'équipe", "Autonomie", "Créativité"],
    "hard_skills": ["UX/UI Design", "Wireframing", "Maquette numérique"],
    "outils": ["figma"],
    "prototype": "projet/SAE301.pdf",
  },
  6: {
      "cover": "mb",
    "name": "Média Bloom",
    "categorie": "Graphisme",
    "contexte": "Dans le cadre d’un projet universitaire en BUT MMI, j’ai réalisé un jeu de société avec des quiz basé sur le multimédia.",
    "objectifs": 'En équipe de trois l’objectif était de créer "une carte de voeux" pour fêter la nouvelle année 2026, de façon original sans format imposé qui changerait des cartes de voeux classiques.',
    "etapes": ["Réalisation d'une carte mental / brainstorming", 
      "Rechercher des idées graphiques", 
      "Établissement des règles, catégories choisis et questions", 
      "Création de la charte graphique",
    "Conception de la maquette du jeu" ],
    "soft_skills": ["Travail d'équipe", "Créativité"],
    "hard_skills": ["Graphisme", "Maquette numérique"],
    "outils": ["figma", "affinity"],
    "prototype": "projet/mb.pdf",
  },
  7: {
      "cover": "spectacle",
    "name": "Spectacles du Trégor",
    "categorie": "UX/UI Design",
    "contexte": "Dans le cadre d’un projet en BUT MMI, j’ai conçu la maquette d’une application mobile dédiée à la scène culturelle du Trégor.",
    "objectifs": "L’enjeu était de centraliser la programmation des cinq principales salles de spectacles du territoire afin d'offrir un accès simplifié aux événements et de dynamiser la promotion de l'activité locale.",
    "etapes": ["Analyse des sources d'information", 
      "Réalisation d'un benchmark", 
      "Recherche de fonctionnalités à proposer", 
      "Création d'un prototype en noir et blanc (Wireframes)",
    "Construction d'une maquette (Mock-up)" ],
    "soft_skills": ["Autonomie", "Recherche et analyse"],
    "hard_skills": ["UX/UI Design", "Wireframing", "Maquette numérique"],
    "outils": ["figma"],
    "prototype": "projet/UI.pdf",
  },
  8: {
      "cover": "diorama",
    "name": "Sugar Rush",
    "categorie": "3D",
    "contexte": "Dans le cadre d’un projet universitaire en BUT MMI, j’ai conçu et modélisé un diorama 3D sous Blender. ",
    "objectifs": "Partant juste d'un cube, j'ai pris en charge l'intégralité du processus créatif : de l'imagination de l'ambiance et de la scénographie jusqu’à la réalisation complète du décor, afin de créer un univers unique et cohérent.",
    "etapes": ["Recherche d'inspiration", 
      "Réalisation de la structure de la scène", 
      "Ajout des couleurs et textures", 
      "Finitions de la scène avec les lumières" ],
    "soft_skills": ["Autonomie", "Créativité"],
    "hard_skills": ["Modélisation 3D"],
    "outils": ["pinterest", "blender"],
    "prototype": "projet/3D.mp4",
  },

}